apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  namespace: default
spec:
  ports:
    - name: url-shortener
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: url-shortener
status:
  loadBalancer: {}