dependencies:
  - name: mysql
    version: 1.6.9
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled
  - name: redis
    version: 16.5.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
