dependencies:
  - name: mysql
    version: 8.8.27
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: redis
    version: 16.5.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
